-- One row per player-season. inningsPitched is the baseball "194.2" notation
-- (thirds of an inning after the dot), so innings are derived from outs.
select
    player_id,
    season,
    name                                   as player_name,
    last_team_id                           as team_id,
    num_teams,
    age,
    gamesPitched                           as games,
    gamesStarted                           as games_started,
    outs,
    outs / 3.0                             as ip,
    battersFaced                           as bf,
    hits,
    homeRuns                               as hr,
    baseOnBalls                            as bb,
    intentionalWalks                       as ibb,
    hitBatsmen                             as hbp,
    strikeOuts                             as so,
    earnedRuns                             as er,
    runs,
    groundOuts                             as go,
    airOuts                                as ao,
    numberOfPitches                        as pitches,
    era,
    whip,
    fip                                    as fip_statsapi,
    xfip                                   as xfip_statsapi,
    fipMinus                               as fip_minus,
    war,
    is_partial,
    fetched_at
from {{ source("raw", "statsapi_pitching") }}
