-- One row per player-season. Counting stats keep their raw values; only
-- renaming and typing happens here.
select
    player_id,
    season,
    name                                   as player_name,
    last_team_id                           as team_id,
    num_teams,
    position                               as primary_position,
    age,
    gamesPlayed                            as games,
    plateAppearances                       as pa,
    atBats                                 as ab,
    hits,
    doubles,
    triples,
    homeRuns                               as hr,
    baseOnBalls                            as bb,
    intentionalWalks                       as ibb,
    hitByPitch                             as hbp,
    strikeOuts                             as so,
    sacFlies                               as sf,
    sacBunts                               as sh,
    catchersInterference                   as ci,
    stolenBases                            as sb,
    caughtStealing                         as cs,
    totalBases                             as tb,
    avg,
    obp,
    slg,
    babip,
    woba,
    wRcPlus                                as wrc_plus,
    war,
    batting                                as batting_runs,
    baseRunning                            as baserunning_runs,
    fielding                               as fielding_runs,
    {{ adapter.quote("positional") }}      as positional_runs,
    is_partial,
    fetched_at
from {{ source("raw", "statsapi_batting") }}
